package main

// ConnectionStatus represents the connection state
type ConnectionStatus int

const (
	DISCONNECTED ConnectionStatus = iota
	CONNECTING
	CONNECTED
	AUTHENTICATED
	FAILED
)

func (cs ConnectionStatus) String() string {
	switch cs {
	case DISCONNECTED:
		return "DISCONNECTED"
	case CONNECTING:
		return "CONNECTING"
	case CONNECTED:
		return "CONNECTED"
	case AUTHENTICATED:
		return "AUTHENTICATED"
	case FAILED:
		return "FAILED"
	default:
		return "UNKNOWN"
	}
}

// OrderType represents the type of order
type OrderType int

const (
	MARKET_BUY OrderType = iota
	MARKET_SELL
	LIMIT_BUY
	LIMIT_SELL
	STOP_BUY
	STOP_SELL
)

func (ot OrderType) String() string {
	switch ot {
	case MARKET_BUY:
		return "MARKET_BUY"
	case MARKET_SELL:
		return "MARKET_SELL"
	case LIMIT_BUY:
		return "LIMIT_BUY"
	case LIMIT_SELL:
		return "LIMIT_SELL"
	case STOP_BUY:
		return "STOP_BUY"
	case STOP_SELL:
		return "STOP_SELL"
	default:
		return "UNKNOWN"
	}
}

// ConfirmationStatus represents order confirmation status
type ConfirmationStatus int

const (
	SENT ConfirmationStatus = iota
	PENDING
	FILLED
	PARTIALLY_FILLED
	CANCELED
	REJECTED
	FAILED_STATUS
)

func (cs ConfirmationStatus) String() string {
	switch cs {
	case SENT:
		return "SENT"
	case PENDING:
		return "PENDING"
	case FILLED:
		return "FILLED"
	case PARTIALLY_FILLED:
		return "PARTIALLY_FILLED"
	case CANCELED:
		return "CANCELED"
	case REJECTED:
		return "REJECTED"
	case FAILED_STATUS:
		return "FAILED"
	default:
		return "UNKNOWN"
	}
}

// type EaSessions struct{
//     std::shared_ptr<boost::asio::ip::tcp::socket> socket;
//     std::shared_ptr<boost::asio::io_context::strand> strand;
// };

// struct TrackingOrderInfo{
//     std::string session_id;
//     uint64_t ticket_id;
// };

// TradeEventType represents types of trade events
type TradeEventType int

const (
	CLOSED_BY_SL TradeEventType = iota
	CLOSED_BY_TP
	CLOSED_BY_ADMIN
	CLOSED_MANUALLY
	MARGIN_CALL
)

func (tet TradeEventType) String() string {
	switch tet {
	case CLOSED_BY_SL:
		return "CLOSED_BY_SL"
	case CLOSED_BY_TP:
		return "CLOSED_BY_TP"
	case CLOSED_BY_ADMIN:
		return "CLOSED_BY_ADMIN"
	case CLOSED_MANUALLY:
		return "CLOSED_MANUALLY"
	case MARGIN_CALL:
		return "MARGIN_CALL"
	default:
		return "UNKNOWN"
	}
}

// MessageType represents the type of message received
type MessageType int

const (
	HELLO MessageType = iota
	CONFIRMATION
	TRADE_EVENT
	STATE_CHANGE
	PONG
	SYMBOLS
	ACCOUNT
	KILL_SWITCH
	KILL_SWITCH_ACK
	UNKNOWN
)

// SymbolInfo stores metadata for broker symbols (used for canonical→broker mapping)
type SymbolInfo struct {
	Symbol       string  // Broker symbol name (e.g., "XAUUSD")
	Path         string  // Symbol path (e.g., "Forex")
	Description  string  // Symbol description (e.g., "Gold vs US Dollar")
	ContractSize float64 // Contract size (e.g., 100.0)
}

// AccountInfo stores account information from EA
type AccountInfo struct {
	Balance    float64 // Account balance
	Equity     float64 // Account equity
	Profit     float64 // Floating P/L
	Margin     float64 // Used margin
	MarginFree float64 // Free margin
}

// OrderState represents whether ticket is an order or position
type OrderState int

const (
	STATE_PENDING_ORDER OrderState = iota // Pending order (LIMIT/STOP not filled yet)
	STATE_OPEN_POSITION                   // Active position in market
	STATE_CLOSED                          // Completed/canceled
)

func (os OrderState) String() string {
	switch os {
	case STATE_PENDING_ORDER:
		return "PENDING_ORDER"
	case STATE_OPEN_POSITION:
		return "OPEN_POSITION"
	case STATE_CLOSED:
		return "CLOSED"
	default:
		return "UNKNOWN"
	}
}

// TrackingOrderInfo tracks order routing information
type TrackingOrderInfo struct {
	SessionID  string
	TicketID   uint64
	OrderState OrderState // Track if it's order or position
	OrderType  OrderType  // Remember original type
	Symbol     string     // Store symbol for reference
	Magic      int64      // Magic number for the session
}

// PlatformConfig holds platform configuration
type PlatformConfig struct {
	PlatformID      string
	PlatformType    string // "MT5"
	Host            string
	Port            uint16
	CredentialsJSON string // Encrypted credentials
}

// Order represents a new order to be sent
type Order struct {
	SessionID     string
	ClientOrderID string // Unique ID generated by our system
	Symbol        string
	Type          OrderType
	Volume        float64
	Price         *float64 // For limit/stop orders (nil if not set)
	StopLoss      *float64
	TakeProfit    *float64
	Magic         int64
}

// OrderModification represents an order modification request
type OrderModification struct {
	TicketID      uint64 // Broker ID
	ClientOrderID string
	NewStopLoss   *float64
	NewTakeProfit *float64
}

// OrderCancellation represents an order cancellation request
type OrderCancellation struct {
	TicketID      uint64
	ClientOrderID string
	Symbol        string
}

// TradeConfirmation represents a response to an order command
type TradeConfirmation struct {
	SessionID          string
	ClientOrderID      string
	Status             ConfirmationStatus
	TicketID           *uint64 // Broker ID if success
	FilledPrice        *float64
	ReasonMessage      *string // In case of failure
	RawBrokerErrorCode *int
}

// TradeEvent represents an asynchronous trade state change
type TradeEvent struct {
	TicketID    uint64
	EventType   TradeEventType
	ClosePrice  float64
	Profit      float64
	Commission  float64
	Swap        float64
	TimestampMs uint64 // Event time
}

// WSCommand represents a WebSocket command for EA control (from Blank 103.pdf)
type WSCommand struct {
	Type         string            `json:"type"`    // "COMMAND"
	Action       string            `json:"action"`  // "CLOSE_POSITIONS", "DELETE_ORDERS", "PARTIAL_CLOSE"
	Filters      map[string]string `json:"filters"` // Criteria like {"pnl": "PROFIT"}, {"side": "BUY"}
	SessionID    string            `json:"session_id"`
	Magic        int64             `json:"magic"`                 // EA magic number for isolation
	PositionID   string            `json:"position_id,omitempty"` // For specific position partial close
	ClosePercent float64           `json:"close_pct,omitempty"`   // 0-100 for partial close
}
